export const LANGUAGE_OPTIONS = [
  { code: "en", label: "English" },
  { code: "hi", label: "हिंदी" },
  { code: "ta", label: "தமிழ்" },
  { code: "ml", label: "മലയാളം" },
  { code: "mr", label: "मराठी" },
  { code: "bn", label: "বাংলা" },
];

const translations = {
  en: {
    home: "Home",
    recipes: "Recipes",
    saved: "Saved",
    language: "Language",
    searchRecipes: "Search recipes...",
    whatsInFridge: "What's in your fridge?",
    fridgeSubtitle:
      "Enter the ingredients you have to find the perfect recipe matches.",
    addIngredient: "+ Add Ingredient",
    popular: "Popular:",
    addedIngredients: "Added Ingredients",
    clearAll: "🗑 Clear All",
    noIngredients: "No ingredients added yet.",
    findRecipes: "Find Recipes",
    finding: "Finding...",
    recipesNow: "We found recipes you can make right now!",
    proTip: "Pro Tip",
    proTipText:
      "Add staple items like flour, oil, and salt for better search results.",
    fastFilter: "Fast Filter",
    fastFilterText:
      "Once you search, you can filter by cooking time and difficulty level.",
    saveForLater: "Save for later",
    saveForLaterText:
      "Sign in to save your current pantry and favorite recipes.",
    browse: "Browse",
    favorites: "Favorites",
    myKitchen: "My Kitchen",
    recipeResults: "Recipe Results",
    favoriteRecipes: "Favorite Recipes",
    myKitchenRecipes: "My Kitchen Recipes",
    foundMatches: "Found {{count}} delicious matches for your craving",
    savedCount: "You saved {{count}} recipes",
    kitchenCount: "Found {{count}} kitchen-friendly recipes",
    grid: "Grid",
    list: "List",
    filters: "Filters",
    dietary: "Dietary",
    timeDifficulty: "Time & Difficulty",
    category: "Category",
    allRecipes: "All Recipes",
    breakfast: "Breakfast",
    dinner: "Dinner",
    desserts: "Desserts",
    under15: "Under 15 mins",
    easyDifficulty: "Easy Difficulty",
    clearFilters: "Clear Filters",
    loadingRecipes: "Loading recipes...",
    noRecipesFound: "No recipes found",
    tryDifferent: "Try different filters or search terms.",
    noFavoritesYet:
      "Abhi tak koi recipe favorite nahi ki hai. Heart icon pe click karo, phir yahan show hogi.",
    saveRecipe: "Save Recipe",
    savedRecipe: "Saved Recipe",
    shareCopied: "Link copied",
    shareFailed: "Share failed",
    back: "Back",
    ingredients: "Ingredients",
    serves: "Serves {{count}}",
    chefsTip: "💡 Chef's Tip",
    nutritionalProfile: "Nutritional Profile",
    calories: "Calories",
    protein: "Protein",
    fat: "Fat",
    carbs: "Carbs",
    youMightAlsoLike: "You might also like",
    addAllToBasket: "Add all to Basket",
    validationAddIngredients:
      "Please add ingredients or type a recipe request first, so I can find the best recipes for you.",
  },
  hi: {
    home: "होम",
    recipes: "रेसिपीज़",
    saved: "सेव्ड",
    language: "भाषा",
    searchRecipes: "रेसिपी खोजें...",
    whatsInFridge: "आपके फ्रिज में क्या है?",
    fridgeSubtitle:
      "आपके पास जो सामग्री है उसे डालें और सही रेसिपी मैच पाएँ।",
    addIngredient: "+ सामग्री जोड़ें",
    popular: "लोकप्रिय:",
    addedIngredients: "जोड़ी गई सामग्री",
    clearAll: "🗑 सब साफ करें",
    noIngredients: "अभी तक कोई सामग्री नहीं जोड़ी गई।",
    findRecipes: "रेसिपी खोजें",
    finding: "खोज रहे हैं...",
    recipesNow: "हमने ऐसी रेसिपीज़ ढूंढीं जो आप अभी बना सकते हैं!",
    proTip: "प्रो टिप",
    proTipText:
      "बेहतर रिज़ल्ट के लिए आटा, तेल और नमक जैसी बेसिक चीजें जोड़ें।",
    fastFilter: "फास्ट फ़िल्टर",
    fastFilterText:
      "खोजने के बाद आप समय और कठिनाई के अनुसार फ़िल्टर कर सकते हैं।",
    saveForLater: "बाद के लिए सेव करें",
    saveForLaterText:
      "अपनी पेंट्री और पसंदीदा रेसिपीज़ सेव करने के लिए साइन इन करें।",
    browse: "ब्राउज़",
    favorites: "फेवरेट्स",
    myKitchen: "मेरा किचन",
    recipeResults: "रेसिपी रिज़ल्ट",
    favoriteRecipes: "फेवरेट रेसिपीज़",
    myKitchenRecipes: "मेरे किचन की रेसिपीज़",
    foundMatches: "आपके लिए {{count}} स्वादिष्ट मैच मिले",
    savedCount: "आपने {{count}} रेसिपीज़ सेव की हैं",
    kitchenCount: "{{count}} किचन-फ्रेंडली रेसिपीज़ मिलीं",
    grid: "ग्रिड",
    list: "लिस्ट",
    filters: "फ़िल्टर",
    dietary: "डायटरी",
    timeDifficulty: "समय और कठिनाई",
    category: "कैटेगरी",
    allRecipes: "सभी रेसिपीज़",
    breakfast: "ब्रेकफास्ट",
    dinner: "डिनर",
    desserts: "डेज़र्ट्स",
    under15: "15 मिनट से कम",
    easyDifficulty: "आसान कठिनाई",
    clearFilters: "फ़िल्टर साफ करें",
    loadingRecipes: "रेसिपीज़ लोड हो रही हैं...",
    noRecipesFound: "कोई रेसिपी नहीं मिली",
    tryDifferent: "अलग फ़िल्टर या खोज शब्द आज़माएँ।",
    noFavoritesYet:
      "अभी तक कोई रेसिपी सेव नहीं है। हार्ट आइकन पर क्लिक करें।",
    saveRecipe: "रेसिपी सेव करें",
    savedRecipe: "रेसिपी सेव हो गई",
    shareCopied: "लिंक कॉपी हो गया",
    shareFailed: "शेयर नहीं हो पाया",
    back: "वापस",
    ingredients: "सामग्री",
    serves: "{{count}} लोगों के लिए",
    chefsTip: "💡 शेफ की टिप",
    nutritionalProfile: "पोषण प्रोफ़ाइल",
    calories: "कैलोरी",
    protein: "प्रोटीन",
    fat: "फैट",
    carbs: "कार्ब्स",
    youMightAlsoLike: "आपको यह भी पसंद आ सकता है",
    addAllToBasket: "सब कुछ बास्केट में जोड़ें",
    validationAddIngredients:
      "कृपया पहले अपनी सामग्री जोड़ें या कोई रेसिपी रिक्वेस्ट लिखें, ताकि मैं आपके लिए सबसे अच्छी रेसिपीज़ ढूंढ सकूं।",
  },
  ta: {
    home: "முகப்பு",
    recipes: "சமையல் குறிப்புகள்",
    saved: "சேமித்தவை",
    language: "மொழி",
    searchRecipes: "சமையல் குறிப்புகளை தேடுங்கள்...",
    whatsInFridge: "உங்கள் ஃபிரிட்ஜில் என்ன இருக்கிறது?",
    fridgeSubtitle:
      "உங்களிடம் உள்ள பொருட்களை உள்ளிட்டு சரியான சமையல் குறிப்புகளை கண்டுபிடியுங்கள்.",
    addIngredient: "+ பொருள் சேர்க்கவும்",
    popular: "பிரபலமானவை:",
    addedIngredients: "சேர்க்கப்பட்ட பொருட்கள்",
    clearAll: "🗑 அனைத்தையும் நீக்கு",
    noIngredients: "இன்னும் எந்த பொருளும் சேர்க்கப்படவில்லை.",
    findRecipes: "சமையல் குறிப்புகளை காண்க",
    finding: "தேடுகிறது...",
    recipesNow: "நீங்கள் இப்போது செய்யக்கூடிய குறிப்புகள் கிடைத்துள்ளன!",
    proTip: "சிறந்த குறிப்புகள்",
    proTipText:
      "மேலும் நல்ல முடிவுகளுக்கு மாவு, எண்ணெய், உப்பு போன்றவற்றையும் சேர்க்கவும்.",
    fastFilter: "விரைவு வடிகட்டி",
    fastFilterText:
      "தேடலுக்கு பின் நேரம் மற்றும் சிரமத்தின் அடிப்படையில் வடிகட்டலாம்.",
    saveForLater: "பிறகு சேமிக்கவும்",
    saveForLaterText:
      "உங்கள் பொருட்கள் மற்றும் பிடித்த குறிப்புகளை சேமிக்க உள்நுழைக.",
    browse: "உலாவு",
    favorites: "பிடித்தவை",
    myKitchen: "என் சமையலறை",
    recipeResults: "சமையல் முடிவுகள்",
    favoriteRecipes: "பிடித்த சமையல் குறிப்புகள்",
    myKitchenRecipes: "என் சமையலறை குறிப்புகள்",
    foundMatches: "{{count}} சுவையான பொருத்தங்கள் கிடைத்தன",
    savedCount: "நீங்கள் {{count}} குறிப்புகளை சேமித்துள்ளீர்கள்",
    kitchenCount: "{{count}} சமையலறை நட்பு குறிப்புகள் கிடைத்தன",
    grid: "கிரிட்",
    list: "பட்டியல்",
    filters: "வடிகட்டிகள்",
    dietary: "உணவு வகை",
    timeDifficulty: "நேரம் & சிரமம்",
    category: "வகை",
    allRecipes: "அனைத்து குறிப்புகள்",
    breakfast: "காலை உணவு",
    dinner: "இரவு உணவு",
    desserts: "இனிப்புகள்",
    under15: "15 நிமிடங்களுக்கு உட்பட்டது",
    easyDifficulty: "எளிய சிரமம்",
    clearFilters: "வடிகட்டிகள் நீக்கு",
    loadingRecipes: "சமையல் குறிப்புகள் ஏற்றப்படுகின்றன...",
    noRecipesFound: "சமையல் குறிப்பு இல்லை",
    tryDifferent: "வேறு வடிகட்டிகள் அல்லது தேடல் சொல்லை முயற்சிக்கவும்.",
    noFavoritesYet: "இன்னும் பிடித்த குறிப்புகள் இல்லை. ஹார்ட் ஐகானை அழுத்தவும்.",
    saveRecipe: "சமையல் குறிப்பை சேமிக்கவும்",
    savedRecipe: "சேமிக்கப்பட்ட குறிப்பு",
    shareCopied: "இணைப்பு நகலெடுக்கப்பட்டது",
    shareFailed: "பகிர்வு தோல்வி",
    back: "பின்செல்",
    ingredients: "பொருட்கள்",
    serves: "{{count}} பேருக்கு",
    chefsTip: "💡 ஷெஃப் குறிப்பு",
    nutritionalProfile: "உணவுசார் தகவல்",
    calories: "காலோரி",
    protein: "புரதம்",
    fat: "கொழுப்பு",
    carbs: "கார்ப்ஸ்",
    youMightAlsoLike: "இது உங்களுக்கு பிடிக்கலாம்",
    addAllToBasket: "அனைத்தையும் கூடைச் சேர்க்கவும்",
    validationAddIngredients:
      "தயவுசெய்து முதலில் பொருட்களைச் சேர்க்கவும் அல்லது ஒரு சமையல் கோரிக்கையை எழுதவும். அப்போதுதான் உங்களுக்கு சிறந்த சமையல் குறிப்புகளை கண்டுபிடிக்க முடியும்.",
  },
  ml: {
    home: "ഹോം",
    recipes: "റെസിപ്പികൾ",
    saved: "സേവ് ചെയ്തത്",
    language: "ഭാഷ",
    searchRecipes: "റെസിപ്പികൾ തിരയുക...",
    whatsInFridge: "നിങ്ങളുടെ ഫ്രിഡ്ജിൽ എന്തുണ്ട്?",
    fridgeSubtitle:
      "നിങ്ങളുടെ കൈവശമുള്ള സാധനങ്ങൾ ചേർത്ത് ശരിയായ റെസിപ്പികൾ കണ്ടെത്തൂ.",
    addIngredient: "+ ചേരുവ ചേർക്കുക",
    popular: "ജനപ്രിയം:",
    addedIngredients: "ചേർത്ത ചേരുവകൾ",
    clearAll: "🗑 എല്ലാം നീക്കുക",
    noIngredients: "ഇനിയും ചേരുവകൾ ചേർത്തിട്ടില്ല.",
    findRecipes: "റെസിപ്പികൾ കണ്ടെത്തുക",
    finding: "തിരയുന്നു...",
    recipesNow: "നിങ്ങൾക്ക് ഇപ്പോൾ തയ്യാറാക്കാവുന്ന റെസിപ്പികൾ കണ്ടെത്തി!",
    proTip: "പ്രോ ടിപ്പ്",
    proTipText:
      "മാവ്, എണ്ണ, ഉപ്പ് പോലുള്ള അടിസ്ഥാന വസ്തുക്കളും ചേർത്താൽ മികച്ച ഫലം കിട്ടും.",
    fastFilter: "വേഗ ഫിൽട്ടർ",
    fastFilterText:
      "തിരച്ചിലിന് ശേഷം സമയം, ബുദ്ധിമുട്ട് എന്നിവ പ്രകാരം ഫിൽട്ടർ ചെയ്യാം.",
    saveForLater: "പിന്നീട് സേവ് ചെയ്യുക",
    saveForLaterText:
      "നിങ്ങളുടെ പാന്ട്രിയും ഇഷ്ട റെസിപ്പികളും സേവ് ചെയ്യാൻ സൈൻ ഇൻ ചെയ്യുക.",
    browse: "ബ്രൗസ്",
    favorites: "പ്രിയപ്പെട്ടത്",
    myKitchen: "എന്റെ അടുക്കള",
    recipeResults: "റെസിപ്പി ഫലങ്ങൾ",
    favoriteRecipes: "പ്രിയപ്പെട്ട റെസിപ്പികൾ",
    myKitchenRecipes: "എന്റെ അടുക്കള റെസിപ്പികൾ",
    foundMatches: "{{count}} രുചിയേറിയ പൊരുത്തങ്ങൾ ലഭിച്ചു",
    savedCount: "നിങ്ങൾ {{count}} റെസിപ്പികൾ സേവ് ചെയ്തിരിക്കുന്നു",
    kitchenCount: "{{count}} kitchen-friendly റെസിപ്പികൾ ലഭിച്ചു",
    grid: "ഗ്രിഡ്",
    list: "ലിസ്റ്റ്",
    filters: "ഫിൽട്ടറുകൾ",
    dietary: "ഡയറ്ററി",
    timeDifficulty: "സമയം & ബുദ്ധിമുട്ട്",
    category: "വിഭാഗം",
    allRecipes: "എല്ലാ റെസിപ്പികളും",
    breakfast: "പ്രഭാതഭക്ഷണം",
    dinner: "റാത്രി ഭക്ഷണം",
    desserts: "ഡെസേർട്ട്",
    under15: "15 മിനിറ്റിനുള്ളിൽ",
    easyDifficulty: "എളുപ്പം",
    clearFilters: "ഫിൽട്ടറുകൾ നീക്കുക",
    loadingRecipes: "റെസിപ്പികൾ ലോഡ് ചെയ്യുന്നു...",
    noRecipesFound: "റെസിപ്പികൾ കണ്ടെത്തിയില്ല",
    tryDifferent: "മറ്റൊരു ഫിൽട്ടർ അല്ലെങ്കിൽ തിരച്ചിൽ പരീക്ഷിക്കുക.",
    noFavoritesYet: "ഇനിയും സേവ് ചെയ്ത റെസിപ്പികളില്ല. ഹാർട്ട് ഐക്കൺ അമർത്തുക.",
    saveRecipe: "റെസിപ്പി സേവ് ചെയ്യുക",
    savedRecipe: "സേവ് ചെയ്ത റെസിപ്പി",
    shareCopied: "ലിങ്ക് കോപ്പിയായി",
    shareFailed: "ഷെയർ പരാജയപ്പെട്ടു",
    back: "തിരികെ",
    ingredients: "ചേരുവകൾ",
    serves: "{{count}} പേർക്ക്",
    chefsTip: "💡 ഷെഫിന്റെ ടിപ്പ്",
    nutritionalProfile: "പോഷക വിവരം",
    calories: "കാലറി",
    protein: "പ്രോട്ടീൻ",
    fat: "കൊഴുപ്പ്",
    carbs: "കാർബ്സ്",
    youMightAlsoLike: "ഇതും നിങ്ങള്‍ക്ക് ഇഷ്ടപ്പെടാം",
    addAllToBasket: "എല്ലാം ബാസ്കറ്റിൽ ചേർക്കുക",
    validationAddIngredients:
      "ദയവായി ആദ്യം ചേരുവകൾ ചേർക്കുക അല്ലെങ്കിൽ ഒരു റെസിപ്പി അഭ്യർത്ഥന എഴുതുക. അപ്പോഴാണ് നിങ്ങൾക്കായി മികച്ച റെസിപ്പികൾ കണ്ടെത്താൻ കഴിയുക.",
  },
  mr: {
    home: "मुख्यपृष्ठ",
    recipes: "रेसिपीज",
    saved: "जतन केलेले",
    language: "भाषा",
    searchRecipes: "रेसिपीज शोधा...",
    whatsInFridge: "तुमच्या फ्रिजमध्ये काय आहे?",
    fridgeSubtitle:
      "तुमच्याकडे असलेल्या साहित्यावरून योग्य रेसिपीज शोधा.",
    addIngredient: "+ साहित्य जोडा",
    popular: "लोकप्रिय:",
    addedIngredients: "जोडलेले साहित्य",
    clearAll: "🗑 सर्व साफ करा",
    noIngredients: "अजून साहित्य जोडलेले नाही.",
    findRecipes: "रेसिपीज शोधा",
    finding: "शोधत आहे...",
    recipesNow: "आम्हाला काही रेसिपीज मिळाल्या ज्या तुम्ही आत्ताच करू शकता!",
    proTip: "प्रो टिप",
    proTipText:
      "चांगल्या निकालांसाठी पीठ, तेल आणि मीठ यांसारख्या वस्तूही जोडा.",
    fastFilter: "फास्ट फिल्टर",
    fastFilterText:
      "शोधल्यानंतर वेळ आणि कठीणतेनुसार फिल्टर करू शकता.",
    saveForLater: "नंतरसाठी जतन करा",
    saveForLaterText:
      "तुमची पँट्री आणि आवडत्या रेसिपीज जतन करण्यासाठी साइन इन करा.",
    browse: "ब्राउझ",
    favorites: "फेव्हरेट्स",
    myKitchen: "माझे किचन",
    recipeResults: "रेसिपी निकाल",
    favoriteRecipes: "फेव्हरेट रेसिपीज",
    myKitchenRecipes: "माझ्या किचनच्या रेसिपीज",
    foundMatches: "तुमच्यासाठी {{count}} स्वादिष्ट पर्याय मिळाले",
    savedCount: "तुम्ही {{count}} रेसिपीज जतन केल्या आहेत",
    kitchenCount: "{{count}} kitchen-friendly रेसिपीज मिळाल्या",
    grid: "ग्रिड",
    list: "यादी",
    filters: "फिल्टर्स",
    dietary: "डायटरी",
    timeDifficulty: "वेळ आणि कठीणता",
    category: "श्रेणी",
    allRecipes: "सर्व रेसिपीज",
    breakfast: "नाश्ता",
    dinner: "डिनर",
    desserts: "डेसर्ट्स",
    under15: "15 मिनिटांच्या आत",
    easyDifficulty: "सोपे",
    clearFilters: "फिल्टर्स साफ करा",
    loadingRecipes: "रेसिपीज लोड होत आहेत...",
    noRecipesFound: "रेसिपीज सापडल्या नाहीत",
    tryDifferent: "वेगळे फिल्टर्स किंवा शोध शब्द वापरा.",
    noFavoritesYet: "अजून फेव्हरेट रेसिपीज नाहीत. हार्ट आयकॉन क्लिक करा.",
    saveRecipe: "रेसिपी जतन करा",
    savedRecipe: "जतन केलेली रेसिपी",
    shareCopied: "लिंक कॉपी झाली",
    shareFailed: "शेअर फेल झाले",
    back: "मागे",
    ingredients: "साहित्य",
    serves: "{{count}} जणांसाठी",
    chefsTip: "💡 शेफ टिप",
    nutritionalProfile: "पोषण माहिती",
    calories: "कॅलरीज",
    protein: "प्रोटीन",
    fat: "फॅट",
    carbs: "कार्ब्स",
    youMightAlsoLike: "तुम्हाला हेही आवडू शकते",
    addAllToBasket: "सर्व बास्केटमध्ये जोडा",
    validationAddIngredients:
      "कृपया आधी साहित्य जोडा किंवा एखादी रेसिपी विनंती लिहा, म्हणजे मी तुमच्यासाठी सर्वोत्तम रेसिपीज शोधू शकेन.",
  },
  bn: {
    home: "হোম",
    recipes: "রেসিপি",
    saved: "সংরক্ষিত",
    language: "ভাষা",
    searchRecipes: "রেসিপি খুঁজুন...",
    whatsInFridge: "আপনার ফ্রিজে কী আছে?",
    fridgeSubtitle:
      "আপনার কাছে থাকা উপকরণ লিখুন এবং সঠিক রেসিপি খুঁজে নিন।",
    addIngredient: "+ উপকরণ যোগ করুন",
    popular: "জনপ্রিয়:",
    addedIngredients: "যোগ করা উপকরণ",
    clearAll: "🗑 সব মুছুন",
    noIngredients: "এখনও কোনো উপকরণ যোগ করা হয়নি।",
    findRecipes: "রেসিপি খুঁজুন",
    finding: "খোঁজা হচ্ছে...",
    recipesNow: "আমরা এমন রেসিপি পেয়েছি যা আপনি এখনই বানাতে পারেন!",
    proTip: "প্রো টিপ",
    proTipText:
      "ভালো ফলের জন্য ময়দা, তেল, লবণ মতো জিনিসও যোগ করুন।",
    fastFilter: "ফাস্ট ফিল্টার",
    fastFilterText:
      "সার্চের পর সময় ও কঠিনতার ভিত্তিতে ফিল্টার করতে পারবেন।",
    saveForLater: "পরে সংরক্ষণ করুন",
    saveForLaterText:
      "আপনার প্যান্ট্রি ও পছন্দের রেসিপি সংরক্ষণ করতে সাইন ইন করুন।",
    browse: "ব্রাউজ",
    favorites: "ফেভারিট",
    myKitchen: "আমার কিচেন",
    recipeResults: "রেসিপি ফলাফল",
    favoriteRecipes: "ফেভারিট রেসিপি",
    myKitchenRecipes: "আমার কিচেন রেসিপি",
    foundMatches: "আপনার জন্য {{count}}টি দারুণ মিল পাওয়া গেছে",
    savedCount: "আপনি {{count}}টি রেসিপি সংরক্ষণ করেছেন",
    kitchenCount: "{{count}}টি kitchen-friendly রেসিপি পাওয়া গেছে",
    grid: "গ্রিড",
    list: "লিস্ট",
    filters: "ফিল্টার",
    dietary: "ডায়েটারি",
    timeDifficulty: "সময় ও কঠিনতা",
    category: "ক্যাটাগরি",
    allRecipes: "সব রেসিপি",
    breakfast: "ব্রেকফাস্ট",
    dinner: "ডিনার",
    desserts: "ডেজার্ট",
    under15: "১৫ মিনিটের কম",
    easyDifficulty: "সহজ স্তর",
    clearFilters: "ফিল্টার পরিষ্কার করুন",
    loadingRecipes: "রেসিপি লোড হচ্ছে...",
    noRecipesFound: "কোনো রেসিপি পাওয়া যায়নি",
    tryDifferent: "অন্য ফিল্টার বা সার্চ শব্দ ব্যবহার করুন।",
    noFavoritesYet: "এখনও কোনো ফেভারিট রেসিপি নেই। হার্ট আইকনে ক্লিক করুন।",
    saveRecipe: "রেসিপি সংরক্ষণ করুন",
    savedRecipe: "সংরক্ষিত রেসিপি",
    shareCopied: "লিংক কপি হয়েছে",
    shareFailed: "শেয়ার ব্যর্থ হয়েছে",
    back: "ফিরুন",
    ingredients: "উপকরণ",
    serves: "{{count}} জনের জন্য",
    chefsTip: "💡 শেফের টিপ",
    nutritionalProfile: "পুষ্টিগুণ",
    calories: "ক্যালোরি",
    protein: "প্রোটিন",
    fat: "ফ্যাট",
    carbs: "কার্বস",
    youMightAlsoLike: "এটাও আপনার ভালো লাগতে পারে",
    addAllToBasket: "সব বক্সে যোগ করুন",
    validationAddIngredients:
      "অনুগ্রহ করে আগে উপকরণ যোগ করুন অথবা একটি রেসিপি অনুরোধ লিখুন, তাহলে আমি আপনার জন্য সেরা রেসিপিগুলো খুঁজে দিতে পারব।",
  },
};

export function getSavedLanguage() {
  if (typeof window === "undefined") return "en";
  return localStorage.getItem("recipehub_language") || "en";
}

export function setSavedLanguage(code) {
  if (typeof window === "undefined") return;
  localStorage.setItem("recipehub_language", code);
}

export function translate(language, key, vars = {}) {
  let text = translations[language]?.[key] ?? translations.en[key] ?? key;
  Object.keys(vars).forEach((name) => {
    text = text.replaceAll(`{{${name}}}`, String(vars[name]));
  });
  return text;
}

export function getUiText(language) {
  return (key, vars = {}) => translate(language, key, vars);
}